name: Notify Discord on Update til
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d '{"content": "The main branch has been updated!"}' \
              $DISCORD_WEBHOOK_URL